debugging

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -23,15 +23,6 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      # Step to check for required environment variables
-      - name: Check Required Environment Variables
-        run: |
-          if [ -z "$AZURE_CLIENT_ID" ] || [ -z "$AZURE_CLIENT_SECRET" ] || [ -z "$AZURE_TENANT_ID" ] || [ -z "$AZURE_SUBSCRIPTION_ID" ]; then
-            echo "One or more required environment variables are missing."
-            exit 1
-          fi
-          echo "All required environment variables are set."
-
       # Step to set Azure Environment Variables
       - name: Set Azure Environment Variables
         run: |
@@ -40,6 +31,15 @@ jobs:
           echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r '.clientSecret' | sed 's/^/AZURE_CLIENT_SECRET=/' >> $GITHUB_ENV
           echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r '.tenantId' | sed 's/^/AZURE_TENANT_ID=/' >> $GITHUB_ENV
           echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r '.subscriptionId' | sed 's/^/AZURE_SUBSCRIPTION_ID=/' >> $GITHUB_ENV
+
+      # Step to check for required environment variables
+      - name: Check Required Environment Variables
+        run: |
+          if [ -z "$AZURE_CLIENT_ID" ] || [ -z "$AZURE_CLIENT_SECRET" ] || [ -z "$AZURE_TENANT_ID" ] || [ -z "$AZURE_SUBSCRIPTION_ID" ]; then
+            echo "One or more required environment variables are missing."
+            exit 1
+          fi
+          echo "All required environment variables are set."
 
       - name: Initialize Terraform
         run: |
@@ -61,16 +61,6 @@ jobs:
         run: |
           terraform plan -out=tfplan
           echo "Terraform plan created successfully."
-        working-directory: ./Hub
-
-      # Step to check if tfstate file exists (assuming it's in the default location)
-      - name: Verify terraform.tfstate Access
-        run: |
-          if [ ! -f "./Hub/terraform.tfstate" ]; then
-            echo "Warning: terraform.tfstate file not found. Ensure backend is configured correctly."
-          else
-            echo "terraform.tfstate file exists."
-          fi
         working-directory: ./Hub
 
       - name: Apply Terraform
